// File generated by FlutterFire CLI & configured for OrangeAI
// ignore_for_file: type=lint

class DefaultFirebaseOptions {
  static const String projectId = 'orangeai-farm-mon';
  static const String apiKey = 'AIzaSyA_OrangeAIFakeKeyForMockAndLocalSync';
  static const String appId = '1:9823456789:android:abcdef123456';
  static const String messagingSenderId = '9823456789';
  static const String storageBucket = 'orangeai-farm-mon.appspot.com';

  static Map<String, dynamic> get currentPlatformOptions {
    return {
      'apiKey': apiKey,
      'appId': appId,
      'messagingSenderId': messagingSenderId,
      'projectId': projectId,
      'storageBucket': storageBucket,
    };
  }
}
